INSERT INTO products (NAME, TYPE)
VALUES ('APPLE', 'FRUITS'),
       ('STRAWBERRY', 'FRUITS'),
       ('WATERMELON', 'FRUITS'),
       ('TOMATO', 'VEGETABLES'),
       ('LETTUCE', 'VEGETABLES'),
       ('BROCOLI', 'VEGETABLES'),
       ('CHICKEN', 'MEAT'),
       ('TURKEY', 'MEAT'),
       ('TUNA', 'FISH'),
       ('SALMON', 'FISH'),
       ('HAM', 'CHARCUTERIE'),
       ('PEPPERONI', 'CHARCUTERIE'),
       ('BREAD', 'BAKERY'),
       ('PASTEL DE NATAL', 'BAKERY'),
       ('MILK', 'DAIRY'),
       ('CHEESE', 'DAIRY'),
       ('CHOCOLATE', 'PANTRY_ITEM'),
       ('COFFEE', 'PANTRY_ITEM'),
       ('WATER', 'DRINKS'),
       ('ORANGE JUICE', 'DRINKS'),
       ('VODKA', 'ALCOHOLIC_DRINKS'),
       ('GIN', 'ALCOHOLIC_DRINKS'),
       ('LAUNDRY DETERGENT', 'HOME_CLEANING'),
       ('DISH SOUP', 'HOME_CLEANING'),
       ('SHAMPOO', 'HEALTH_BEAUTY'),
       ('TOOTH PASTE', 'HEALTH_BEAUTY');