INSERT INTO products (NAME, TYPE, image_url)
VALUES ('Apple', 'FRUITS', '/images/apple.png'),
        ('Strawberry', 'FRUITS', '/images/apple.png'),
        ('Watermelon', 'FRUITS', '/images/apple.png'),
        ('Pear', 'FRUITS', '/images/apple.png'),
        ('Grape', 'FRUITS', '/images/apple.png'),
        ('Tangerine', 'FRUITS', '/images/apple.png'),
        ('Orange', 'FRUITS', '/images/apple.png'),
        ('Lemon', 'FRUITS', '/images/apple.png'),
        ('Lime', 'FRUITS', '/images/apple.png'),
        ('Blueberry', 'FRUITS', '/images/apple.png'),
        ('Kiwi', 'FRUITS', '/images/apple.png'),
        ('Avocado', 'FRUITS', '/images/apple.png'),
        ('Peach', 'FRUITS', '/images/apple.png'),
        ('Melon', 'FRUITS', '/images/apple.png'),
        ('Mango', 'FRUITS', '/images/apple.png'),
        ('Papaya', 'FRUITS', '/images/apple.png'),
        ('Raspberry', 'FRUITS', '/images/apple.png'),
        ('Blackberry', 'FRUITS', '/images/apple.png'),
        ('Pineapple', 'FRUITS', '/images/apple.png'),
        ('Plum', 'FRUITS', '/images/apple.png'),
        ('Fig', 'FRUITS', '/images/apple.png'),
        ('Pomegranate', 'FRUITS', '/images/apple.png'),
        ('Passion fruit', 'FRUITS', '/images/apple.png'),
        ('Tomato', 'VEGETABLES', '/images/apple.png'),
        ('Cherry tomato', 'VEGETABLES', '/images/apple.png'),
        ('Lettuce', 'VEGETABLES', '/images/apple.png'),
        ('Broccoli', 'VEGETABLES', '/images/apple.png'),
        ('Carrot', 'VEGETABLES', '/images/apple.png'),
        ('Zucchini', 'VEGETABLES', '/images/apple.png'),
        ('Sweet potato', 'VEGETABLES', '/images/apple.png'),
        ('Potato', 'VEGETABLES', '/images/apple.png'),
        ('Onion', 'VEGETABLES', '/images/apple.png'),
        ('Garlic', 'VEGETABLES', '/images/apple.png'),
        ('Spinach', 'VEGETABLES', '/images/apple.png'),
        ('Leek', 'VEGETABLES', '/images/apple.png'),
        ('Cauliflower', 'VEGETABLES', '/images/apple.png'),
        ('Coriander', 'VEGETABLES', '/images/apple.png'),
        ('Parsley', 'VEGETABLES', '/images/apple.png'),
        ('Mushroom', 'VEGETABLES', '/images/apple.png'),
        ('Peppers', 'VEGETABLES', '/images/apple.png'),
        ('Asparagus', 'VEGETABLES', '/images/apple.png'),
        ('Arugula', 'VEGETABLES', '/images/apple.png'),
        ('Olives', 'VEGETABLES', '/images/apple.png'),
        ('Red onion', 'VEGETABLES', '/images/apple.png'),
        ('Cabbage', 'VEGETABLES', '/images/apple.png'),
        ('Red cabbage', 'VEGETABLES', '/images/apple.png'),
        ('Green beans', 'VEGETABLES', '/images/apple.png'),
        ('Turnip', 'VEGETABLES', '/images/apple.png'),
        ('Collard', 'VEGETABLES', '/images/apple.png'),
        ('Pumpkin', 'VEGETABLES', '/images/apple.png'),
        ('Eggplant', 'VEGETABLES', '/images/apple.png'),
        ('Cucumber', 'VEGETABLES', '/images/apple.png'),
        ('Celery', 'VEGETABLES', '/images/apple.png'),
        ('Basil', 'VEGETABLES', '/images/apple.png'),
        ('Oregano', 'VEGETABLES', '/images/apple.png'),
        ('Chives', 'VEGETABLES', '/images/apple.png'),
        ('Ginger', 'VEGETABLES', '/images/apple.png'),
        ('Chicken', 'MEAT', '/images/apple.png'),
        ('Turkey', 'MEAT', '/images/apple.png'),
        ('Tuna', 'FISH', '/images/apple.png'),
        ('Salmon', 'FISH', '/images/apple.png'),
        ('Ham', 'CHARCUTERIE', '/images/apple.png'),
        ('Pepperoni', 'CHARCUTERIE', '/images/apple.png'),
        ('Bread', 'BAKERY', '/images/apple.png'),
        ('Pastel de natal', 'BAKERY', '/images/apple.png'),
        ('Milk', 'DAIRY', '/images/apple.png'),
        ('Cheese', 'DAIRY', '/images/apple.png'),
        ('Chocolate', 'PANTRYITEM', '/images/apple.png'),
        ('Coffee', 'PANTRYITEM', '/images/apple.png'),
        ('Water', 'DRINKS', '/images/apple.png'),
        ('Orange juice', 'DRINKS', '/images/apple.png'),
        ('Vodka', 'ALCOHOLICDRINKS', '/images/apple.png'),
        ('Gin', 'ALCOHOLICDRINKS', '/images/apple.png'),
        ('Laundry detergent', 'HOMECLEANING', '/images/apple.png'),
        ('Dish soup', 'HOMECLEANING', '/images/apple.png'),
        ('Shampoo', 'HEALTHBEAUTY', '/images/apple.png'),
        ('Tooth paste', 'HEALTHBEAUTY', '/images/apple.png');


