INSERT INTO products (NAME, TYPE, image_url)
VALUES ('Apple', 'FRUITS', '/images/fruits/apple.png'),
       ('Banana', 'FRUITS', '/images/fruits/banana.png'),
       ('Strawberry', 'FRUITS', '/images/fruits/strawberry.png'),
       ('Watermelon', 'FRUITS', '/images/fruits/watermelon.png'),
       ('Pear', 'FRUITS', '/images/fruits/pear.png'),
       ('Grapes', 'FRUITS', '/images/fruits/grapes.png'),
       ('Tangerine', 'FRUITS', '/images/fruits/tangerine.png'),
       ('Orange', 'FRUITS', '/images/fruits/orange.png'),
       ('Lemon', 'FRUITS', '/images/fruits/lemon.png'),
       ('Lime', 'FRUITS', '/images/fruits/lime.png'),
       ('Blueberry', 'FRUITS', '/images/fruits/blueberry.png'),
       ('Kiwi', 'FRUITS', '/images/fruits/kiwi.png'),
       ('Avocado', 'FRUITS', '/images/fruits/avocado.png'),
       ('Peach', 'FRUITS', '/images/fruits/peach.png'),
       ('Melon', 'FRUITS', '/images/fruits/melon.png'),
       ('Mango', 'FRUITS', '/images/fruits/mango.png'),
       ('Papaya', 'FRUITS', '/images/fruits/papaya.png'),
       ('Raspberry', 'FRUITS', '/images/fruits/raspberry.png'),
       ('Blackberry', 'FRUITS', '/images/fruits/blackberry.png'),
       ('Pineapple', 'FRUITS', '/images/fruits/pineapple.png'),
       ('Plum', 'FRUITS', '/images/fruits/plum.png'),
       ('Fig', 'FRUITS', '/images/fruits/fig.png'),
       ('Pomegranate', 'FRUITS', '/images/fruits/pomegranate.png'),
       ('Passion fruit', 'FRUITS', '/images/fruits/passion_fruit.png'),
       ('Tomato', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Cherry tomato', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Lettuce', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Broccoli', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Carrot', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Zucchini', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Sweet potato', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Potato', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Onion', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Garlic', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Spinach', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Leek', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Cauliflower', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Coriander', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Parsley', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Mushroom', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Peppers', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Asparagus', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Arugula', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Olives', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Red onion', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Cabbage', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Red cabbage', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Green beans', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Turnip', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Collard', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Pumpkin', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Eggplant', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Cucumber', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Celery', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Basil', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Oregano', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Chives', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Ginger', 'VEGETABLES', '/images/fruits/apple.png'),
       ('Chicken', 'MEAT', '/images/fruits/apple.png'),
       ('Turkey', 'MEAT', '/images/fruits/apple.png'),
       ('Tuna', 'FISH', '/images/fruits/apple.png'),
       ('Salmon', 'FISH', '/images/fruits/apple.png'),
       ('Ham', 'CHARCUTERIE', '/images/fruits/apple.png'),
       ('Pepperoni', 'CHARCUTERIE', '/images/fruits/apple.png'),
       ('Bread', 'BAKERY', '/images/fruits/apple.png'),
       ('Pastel de natal', 'BAKERY', '/images/fruits/apple.png'),
       ('Milk', 'DAIRY', '/images/fruits/apple.png'),
       ('Cheese', 'DAIRY', '/images/fruits/apple.png'),
       ('Rice', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Pasta', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Couscous', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Beans', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Flour', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Baking Powder', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Wraps', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Olive Oil', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Vegetable Oil', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Vinegar', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Soy Sauce', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Hot Sauce', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Mustard', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Ketchup', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Mayonnaise', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Tomato Paste', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Corn', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Tuna', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Salt', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Sugar', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Biscuits', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Cereal', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Chips', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Popcorn', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Coffee', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Tea', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Cocoa Powder', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Chocolate', 'PANTRYITEM', '/images/fruits/apple.png'),
       ('Water', 'DRINKS', '/images/fruits/apple.png'),
       ('Orange juice', 'DRINKS', '/images/fruits/apple.png'),
       ('Vodka', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Gin', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Rum', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Whiskey', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Tequila', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Brandy', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Beer', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Cider', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Red Wine', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('White Wine', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Rosé Wine', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Champagne', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Port Wine', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Liqueur', 'ALCOHOLICDRINKS', '/images/fruits/apple.png'),
       ('Laundry Detergent', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Dish Soap', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Dishwasher Tablets', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Glass Cleaner', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Floor Cleaner', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Kitchen Degreaser', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Bleach', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Toilet Bowl Cleaner', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Air Freshener', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Garbage Bags', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Paper Towels', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Sponges', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Rubber Gloves', 'HOMECLEANING', '/images/fruits/apple.png'),
       ('Shampoo', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Conditioner', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Toothpaste', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Toothbrush', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Mouthwash', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Soap', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Body Wash', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Deodorant', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Body Lotion', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Face Cream', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Sunscreen', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Hand Sanitizer', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Razor', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Shaving Cream', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Perfume', 'HEALTHBEAUTY', '/images/fruits/apple.png'),
       ('Makeup Remover', 'HEALTHBEAUTY', '/images/fruits/apple.png'),



